

default: &default
  adapter: postgresql
  encoding: utf8
  pool: 5
  timeout: 5000

development:
  <<: *default
  database: db/development_postgresql

test:
  <<: *default
  database: db/test_postgresql

production:
  <<: *default
  database: db/production_postgresql
